// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: process.proto

package process

/*
Package process provides a data model for process manager plugin template
*/

import proto "github.com/gogo/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

type Template struct {
	Name                 string            `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Cmd                  string            `protobuf:"bytes,2,opt,name=cmd,proto3" json:"cmd,omitempty"`
	POptions             *TemplatePOptions `protobuf:"bytes,3,opt,name=p_options,json=pOptions" json:"p_options,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Template) Reset()         { *m = Template{} }
func (m *Template) String() string { return proto.CompactTextString(m) }
func (*Template) ProtoMessage()    {}
func (*Template) Descriptor() ([]byte, []int) {
	return fileDescriptor_process_fda39250a8ee1067, []int{0}
}
func (m *Template) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Template.Unmarshal(m, b)
}
func (m *Template) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Template.Marshal(b, m, deterministic)
}
func (dst *Template) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Template.Merge(dst, src)
}
func (m *Template) XXX_Size() int {
	return xxx_messageInfo_Template.Size(m)
}
func (m *Template) XXX_DiscardUnknown() {
	xxx_messageInfo_Template.DiscardUnknown(m)
}

var xxx_messageInfo_Template proto.InternalMessageInfo

func (m *Template) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Template) GetCmd() string {
	if m != nil {
		return m.Cmd
	}
	return ""
}

func (m *Template) GetPOptions() *TemplatePOptions {
	if m != nil {
		return m.POptions
	}
	return nil
}

type TemplatePOptions struct {
	Args                 []string `protobuf:"bytes,1,rep,name=args" json:"args,omitempty"`
	Restart              int32    `protobuf:"varint,2,opt,name=restart,proto3" json:"restart,omitempty"`
	Detach               bool     `protobuf:"varint,3,opt,name=detach,proto3" json:"detach,omitempty"`
	RunOnStartup         bool     `protobuf:"varint,4,opt,name=run_on_startup,json=runOnStartup,proto3" json:"run_on_startup,omitempty"`
	Notify               bool     `protobuf:"varint,5,opt,name=notify,proto3" json:"notify,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TemplatePOptions) Reset()         { *m = TemplatePOptions{} }
func (m *TemplatePOptions) String() string { return proto.CompactTextString(m) }
func (*TemplatePOptions) ProtoMessage()    {}
func (*TemplatePOptions) Descriptor() ([]byte, []int) {
	return fileDescriptor_process_fda39250a8ee1067, []int{0, 0}
}
func (m *TemplatePOptions) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TemplatePOptions.Unmarshal(m, b)
}
func (m *TemplatePOptions) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TemplatePOptions.Marshal(b, m, deterministic)
}
func (dst *TemplatePOptions) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TemplatePOptions.Merge(dst, src)
}
func (m *TemplatePOptions) XXX_Size() int {
	return xxx_messageInfo_TemplatePOptions.Size(m)
}
func (m *TemplatePOptions) XXX_DiscardUnknown() {
	xxx_messageInfo_TemplatePOptions.DiscardUnknown(m)
}

var xxx_messageInfo_TemplatePOptions proto.InternalMessageInfo

func (m *TemplatePOptions) GetArgs() []string {
	if m != nil {
		return m.Args
	}
	return nil
}

func (m *TemplatePOptions) GetRestart() int32 {
	if m != nil {
		return m.Restart
	}
	return 0
}

func (m *TemplatePOptions) GetDetach() bool {
	if m != nil {
		return m.Detach
	}
	return false
}

func (m *TemplatePOptions) GetRunOnStartup() bool {
	if m != nil {
		return m.RunOnStartup
	}
	return false
}

func (m *TemplatePOptions) GetNotify() bool {
	if m != nil {
		return m.Notify
	}
	return false
}

func init() {
	proto.RegisterType((*Template)(nil), "process.Template")
	proto.RegisterType((*TemplatePOptions)(nil), "process.Template.pOptions")
}

func init() { proto.RegisterFile("process.proto", fileDescriptor_process_fda39250a8ee1067) }

var fileDescriptor_process_fda39250a8ee1067 = []byte{
	// 213 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x3c, 0x90, 0xbb, 0x4e, 0xc4, 0x30,
	0x10, 0x45, 0x65, 0xf2, 0x1e, 0x1e, 0x42, 0x53, 0x20, 0x2b, 0x55, 0x84, 0x28, 0x52, 0xa5, 0x80,
	0x82, 0xcf, 0x88, 0x64, 0xe8, 0x23, 0x93, 0x18, 0x88, 0x44, 0x6c, 0xcb, 0x76, 0x0a, 0x7e, 0x62,
	0x3f, 0x78, 0xab, 0x95, 0xed, 0x78, 0xbb, 0x7b, 0xc6, 0x33, 0xf7, 0x48, 0x86, 0x7b, 0x6d, 0xd4,
	0x2c, 0xac, 0x1d, 0xb4, 0x51, 0x4e, 0x61, 0x75, 0xe0, 0xf3, 0x99, 0x40, 0xfd, 0x29, 0x36, 0xfd,
	0xc7, 0x9d, 0x40, 0x84, 0x5c, 0xf2, 0x4d, 0x50, 0xd2, 0x91, 0xbe, 0x61, 0x21, 0xe3, 0x23, 0x64,
	0xf3, 0xb6, 0xd0, 0x9b, 0x30, 0xf2, 0x11, 0xdf, 0xa1, 0xd1, 0x93, 0xd2, 0x6e, 0x55, 0xd2, 0xd2,
	0xac, 0x23, 0xfd, 0xed, 0x6b, 0x3b, 0xa4, 0xfa, 0xd4, 0x35, 0xe8, 0x31, 0x6e, 0xb0, 0x3a, 0xa5,
	0xf6, 0x44, 0xe0, 0x0a, 0xde, 0xc5, 0xcd, 0x8f, 0xa5, 0xa4, 0xcb, 0xbc, 0xcb, 0x67, 0xa4, 0x50,
	0x19, 0x61, 0x1d, 0x37, 0x2e, 0xf8, 0x0a, 0x96, 0x10, 0x9f, 0xa0, 0x5c, 0x84, 0xe3, 0xf3, 0x6f,
	0x10, 0xd6, 0xec, 0x20, 0x7c, 0x81, 0x07, 0xb3, 0xcb, 0x49, 0xc9, 0x29, 0xec, 0xed, 0x9a, 0xe6,
	0xe1, 0xfd, 0xce, 0xec, 0x72, 0x94, 0x1f, 0x71, 0xe6, 0xaf, 0xa5, 0x72, 0xeb, 0xf7, 0x3f, 0x2d,
	0xe2, 0x75, 0xa4, 0xaf, 0x32, 0x7c, 0xc6, 0xdb, 0x25, 0x00, 0x00, 0xff, 0xff, 0xc8, 0x22, 0xd9,
	0xd8, 0x1d, 0x01, 0x00, 0x00,
}
