// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.17.3
// source: datamsg.proto

//import "google/protobuf/timestamp.proto";

package msg

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PutDel int32

const (
	PutDel_PUT PutDel = 0
	PutDel_DEL PutDel = 1
)

// Enum value maps for PutDel.
var (
	PutDel_name = map[int32]string{
		0: "PUT",
		1: "DEL",
	}
	PutDel_value = map[string]int32{
		"PUT": 0,
		"DEL": 1,
	}
)

func (x PutDel) Enum() *PutDel {
	p := new(PutDel)
	*p = x
	return p
}

func (x PutDel) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PutDel) Descriptor() protoreflect.EnumDescriptor {
	return file_datamsg_proto_enumTypes[0].Descriptor()
}

func (PutDel) Type() protoreflect.EnumType {
	return &file_datamsg_proto_enumTypes[0]
}

func (x PutDel) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PutDel.Descriptor instead.
func (PutDel) EnumDescriptor() ([]byte, []int) {
	return file_datamsg_proto_rawDescGZIP(), []int{0}
}

type DataMsgRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MsgId       *Seq                 `protobuf:"bytes,1,opt,name=msgId,proto3" json:"msgId,omitempty"`
	Txn         *Seq                 `protobuf:"bytes,2,opt,name=txn,proto3" json:"txn,omitempty"` //TODO remove this
	DataChanges []*DataChangeRequest `protobuf:"bytes,3,rep,name=dataChanges,proto3" json:"dataChanges,omitempty"`
	DataResyncs []*DataResyncRequest `protobuf:"bytes,4,rep,name=dataResyncs,proto3" json:"dataResyncs,omitempty"` //use max 1
}

func (x *DataMsgRequest) Reset() {
	*x = DataMsgRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_datamsg_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DataMsgRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataMsgRequest) ProtoMessage() {}

func (x *DataMsgRequest) ProtoReflect() protoreflect.Message {
	mi := &file_datamsg_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataMsgRequest.ProtoReflect.Descriptor instead.
func (*DataMsgRequest) Descriptor() ([]byte, []int) {
	return file_datamsg_proto_rawDescGZIP(), []int{0}
}

func (x *DataMsgRequest) GetMsgId() *Seq {
	if x != nil {
		return x.MsgId
	}
	return nil
}

func (x *DataMsgRequest) GetTxn() *Seq {
	if x != nil {
		return x.Txn
	}
	return nil
}

func (x *DataMsgRequest) GetDataChanges() []*DataChangeRequest {
	if x != nil {
		return x.DataChanges
	}
	return nil
}

func (x *DataMsgRequest) GetDataResyncs() []*DataResyncRequest {
	if x != nil {
		return x.DataResyncs
	}
	return nil
}

type DataResyncRequests struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MsgId       *Seq                 `protobuf:"bytes,1,opt,name=msgId,proto3" json:"msgId,omitempty"`
	DataResyncs []*DataResyncRequest `protobuf:"bytes,2,rep,name=dataResyncs,proto3" json:"dataResyncs,omitempty"`
}

func (x *DataResyncRequests) Reset() {
	*x = DataResyncRequests{}
	if protoimpl.UnsafeEnabled {
		mi := &file_datamsg_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DataResyncRequests) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataResyncRequests) ProtoMessage() {}

func (x *DataResyncRequests) ProtoReflect() protoreflect.Message {
	mi := &file_datamsg_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataResyncRequests.ProtoReflect.Descriptor instead.
func (*DataResyncRequests) Descriptor() ([]byte, []int) {
	return file_datamsg_proto_rawDescGZIP(), []int{1}
}

func (x *DataResyncRequests) GetMsgId() *Seq {
	if x != nil {
		return x.MsgId
	}
	return nil
}

func (x *DataResyncRequests) GetDataResyncs() []*DataResyncRequest {
	if x != nil {
		return x.DataResyncs
	}
	return nil
}

type DataResyncReplies struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MsgId       *Seq                                  `protobuf:"bytes,1,opt,name=msgId,proto3" json:"msgId,omitempty"`
	Error       *Error                                `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	DataResyncs *DataResyncReplies_DataResyncsReplies `protobuf:"bytes,3,opt,name=dataResyncs,proto3" json:"dataResyncs,omitempty"`
}

func (x *DataResyncReplies) Reset() {
	*x = DataResyncReplies{}
	if protoimpl.UnsafeEnabled {
		mi := &file_datamsg_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DataResyncReplies) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataResyncReplies) ProtoMessage() {}

func (x *DataResyncReplies) ProtoReflect() protoreflect.Message {
	mi := &file_datamsg_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataResyncReplies.ProtoReflect.Descriptor instead.
func (*DataResyncReplies) Descriptor() ([]byte, []int) {
	return file_datamsg_proto_rawDescGZIP(), []int{2}
}

func (x *DataResyncReplies) GetMsgId() *Seq {
	if x != nil {
		return x.MsgId
	}
	return nil
}

func (x *DataResyncReplies) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

func (x *DataResyncReplies) GetDataResyncs() *DataResyncReplies_DataResyncsReplies {
	if x != nil {
		return x.DataResyncs
	}
	return nil
}

type DataMsgReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MsgId       *Seq                             `protobuf:"bytes,1,opt,name=msgId,proto3" json:"msgId,omitempty"`
	Error       *Error                           `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	DataChanges *DataMsgReply_DataChangesReplies `protobuf:"bytes,3,opt,name=dataChanges,proto3" json:"dataChanges,omitempty"`
	DataResyncs *DataMsgReply_DataResyncsReplies `protobuf:"bytes,4,opt,name=dataResyncs,proto3" json:"dataResyncs,omitempty"`
}

func (x *DataMsgReply) Reset() {
	*x = DataMsgReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_datamsg_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DataMsgReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataMsgReply) ProtoMessage() {}

func (x *DataMsgReply) ProtoReflect() protoreflect.Message {
	mi := &file_datamsg_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataMsgReply.ProtoReflect.Descriptor instead.
func (*DataMsgReply) Descriptor() ([]byte, []int) {
	return file_datamsg_proto_rawDescGZIP(), []int{3}
}

func (x *DataMsgReply) GetMsgId() *Seq {
	if x != nil {
		return x.MsgId
	}
	return nil
}

func (x *DataMsgReply) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

func (x *DataMsgReply) GetDataChanges() *DataMsgReply_DataChangesReplies {
	if x != nil {
		return x.DataChanges
	}
	return nil
}

func (x *DataMsgReply) GetDataResyncs() *DataMsgReply_DataResyncsReplies {
	if x != nil {
		return x.DataResyncs
	}
	return nil
}

type DataChangeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key           string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	OperationType PutDel `protobuf:"varint,2,opt,name=operationType,proto3,enum=msg.PutDel" json:"operationType,omitempty"`
	Content       []byte `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	ContentType   string `protobuf:"bytes,4,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
}

func (x *DataChangeRequest) Reset() {
	*x = DataChangeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_datamsg_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DataChangeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataChangeRequest) ProtoMessage() {}

func (x *DataChangeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_datamsg_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataChangeRequest.ProtoReflect.Descriptor instead.
func (*DataChangeRequest) Descriptor() ([]byte, []int) {
	return file_datamsg_proto_rawDescGZIP(), []int{4}
}

func (x *DataChangeRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *DataChangeRequest) GetOperationType() PutDel {
	if x != nil {
		return x.OperationType
	}
	return PutDel_PUT
}

func (x *DataChangeRequest) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *DataChangeRequest) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

type DataChangeReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key           string `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	OperationType PutDel `protobuf:"varint,3,opt,name=operationType,proto3,enum=msg.PutDel" json:"operationType,omitempty"`
	// zero means success
	Result uint32 `protobuf:"varint,4,opt,name=result,proto3" json:"result,omitempty"`
}

func (x *DataChangeReply) Reset() {
	*x = DataChangeReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_datamsg_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DataChangeReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataChangeReply) ProtoMessage() {}

func (x *DataChangeReply) ProtoReflect() protoreflect.Message {
	mi := &file_datamsg_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataChangeReply.ProtoReflect.Descriptor instead.
func (*DataChangeReply) Descriptor() ([]byte, []int) {
	return file_datamsg_proto_rawDescGZIP(), []int{5}
}

func (x *DataChangeReply) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *DataChangeReply) GetOperationType() PutDel {
	if x != nil {
		return x.OperationType
	}
	return PutDel_PUT
}

func (x *DataChangeReply) GetResult() uint32 {
	if x != nil {
		return x.Result
	}
	return 0
}

type DataResyncRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key         string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Content     []byte `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	ContentType string `protobuf:"bytes,3,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
}

func (x *DataResyncRequest) Reset() {
	*x = DataResyncRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_datamsg_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DataResyncRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataResyncRequest) ProtoMessage() {}

func (x *DataResyncRequest) ProtoReflect() protoreflect.Message {
	mi := &file_datamsg_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataResyncRequest.ProtoReflect.Descriptor instead.
func (*DataResyncRequest) Descriptor() ([]byte, []int) {
	return file_datamsg_proto_rawDescGZIP(), []int{6}
}

func (x *DataResyncRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *DataResyncRequest) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *DataResyncRequest) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

type DataResyncReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ResyncId *Seq   `protobuf:"bytes,1,opt,name=resyncId,proto3" json:"resyncId,omitempty"`
	Key      string `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	// zero means success
	Result uint32 `protobuf:"varint,3,opt,name=result,proto3" json:"result,omitempty"`
}

func (x *DataResyncReply) Reset() {
	*x = DataResyncReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_datamsg_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DataResyncReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataResyncReply) ProtoMessage() {}

func (x *DataResyncReply) ProtoReflect() protoreflect.Message {
	mi := &file_datamsg_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataResyncReply.ProtoReflect.Descriptor instead.
func (*DataResyncReply) Descriptor() ([]byte, []int) {
	return file_datamsg_proto_rawDescGZIP(), []int{7}
}

func (x *DataResyncReply) GetResyncId() *Seq {
	if x != nil {
		return x.ResyncId
	}
	return nil
}

func (x *DataResyncReply) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *DataResyncReply) GetResult() uint32 {
	if x != nil {
		return x.Result
	}
	return 0
}

type ResyncNeededCallback struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MsgId *Seq `protobuf:"bytes,1,opt,name=msgId,proto3" json:"msgId,omitempty"`
	// Optional
	Error *Error `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *ResyncNeededCallback) Reset() {
	*x = ResyncNeededCallback{}
	if protoimpl.UnsafeEnabled {
		mi := &file_datamsg_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResyncNeededCallback) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResyncNeededCallback) ProtoMessage() {}

func (x *ResyncNeededCallback) ProtoReflect() protoreflect.Message {
	mi := &file_datamsg_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResyncNeededCallback.ProtoReflect.Descriptor instead.
func (*ResyncNeededCallback) Descriptor() ([]byte, []int) {
	return file_datamsg_proto_rawDescGZIP(), []int{8}
}

func (x *ResyncNeededCallback) GetMsgId() *Seq {
	if x != nil {
		return x.MsgId
	}
	return nil
}

func (x *ResyncNeededCallback) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

type Seq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The server that generates this seq
	Originator string `protobuf:"bytes,1,opt,name=originator,proto3" json:"originator,omitempty"`
	// UNIX Timestamp of seqence restart
	// google.protobuf.Timestamp seqCreated = 2;
	SeqCreatedSec int64 `protobuf:"varint,2,opt,name=seqCreatedSec,proto3" json:"seqCreatedSec,omitempty"`
	// Sequence
	Seq uint32 `protobuf:"varint,4,opt,name=seq,proto3" json:"seq,omitempty"`
}

func (x *Seq) Reset() {
	*x = Seq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_datamsg_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Seq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Seq) ProtoMessage() {}

func (x *Seq) ProtoReflect() protoreflect.Message {
	mi := &file_datamsg_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Seq.ProtoReflect.Descriptor instead.
func (*Seq) Descriptor() ([]byte, []int) {
	return file_datamsg_proto_rawDescGZIP(), []int{9}
}

func (x *Seq) GetOriginator() string {
	if x != nil {
		return x.Originator
	}
	return ""
}

func (x *Seq) GetSeqCreatedSec() int64 {
	if x != nil {
		return x.SeqCreatedSec
	}
	return 0
}

func (x *Seq) GetSeq() uint32 {
	if x != nil {
		return x.Seq
	}
	return 0
}

type Error struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *Error) Reset() {
	*x = Error{}
	if protoimpl.UnsafeEnabled {
		mi := &file_datamsg_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Error) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Error) ProtoMessage() {}

func (x *Error) ProtoReflect() protoreflect.Message {
	mi := &file_datamsg_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Error.ProtoReflect.Descriptor instead.
func (*Error) Descriptor() ([]byte, []int) {
	return file_datamsg_proto_rawDescGZIP(), []int{10}
}

func (x *Error) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type PingRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *PingRequest) Reset() {
	*x = PingRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_datamsg_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingRequest) ProtoMessage() {}

func (x *PingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_datamsg_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingRequest.ProtoReflect.Descriptor instead.
func (*PingRequest) Descriptor() ([]byte, []int) {
	return file_datamsg_proto_rawDescGZIP(), []int{11}
}

func (x *PingRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type PingReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *PingReply) Reset() {
	*x = PingReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_datamsg_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PingReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingReply) ProtoMessage() {}

func (x *PingReply) ProtoReflect() protoreflect.Message {
	mi := &file_datamsg_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingReply.ProtoReflect.Descriptor instead.
func (*PingReply) Descriptor() ([]byte, []int) {
	return file_datamsg_proto_rawDescGZIP(), []int{12}
}

func (x *PingReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type DataResyncReplies_DataResyncsReplies struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Replies []*DataResyncReply `protobuf:"bytes,1,rep,name=replies,proto3" json:"replies,omitempty"`
}

func (x *DataResyncReplies_DataResyncsReplies) Reset() {
	*x = DataResyncReplies_DataResyncsReplies{}
	if protoimpl.UnsafeEnabled {
		mi := &file_datamsg_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DataResyncReplies_DataResyncsReplies) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataResyncReplies_DataResyncsReplies) ProtoMessage() {}

func (x *DataResyncReplies_DataResyncsReplies) ProtoReflect() protoreflect.Message {
	mi := &file_datamsg_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataResyncReplies_DataResyncsReplies.ProtoReflect.Descriptor instead.
func (*DataResyncReplies_DataResyncsReplies) Descriptor() ([]byte, []int) {
	return file_datamsg_proto_rawDescGZIP(), []int{2, 0}
}

func (x *DataResyncReplies_DataResyncsReplies) GetReplies() []*DataResyncReply {
	if x != nil {
		return x.Replies
	}
	return nil
}

type DataMsgReply_DataChangesReplies struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Replies []*DataChangeReply `protobuf:"bytes,1,rep,name=replies,proto3" json:"replies,omitempty"`
}

func (x *DataMsgReply_DataChangesReplies) Reset() {
	*x = DataMsgReply_DataChangesReplies{}
	if protoimpl.UnsafeEnabled {
		mi := &file_datamsg_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DataMsgReply_DataChangesReplies) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataMsgReply_DataChangesReplies) ProtoMessage() {}

func (x *DataMsgReply_DataChangesReplies) ProtoReflect() protoreflect.Message {
	mi := &file_datamsg_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataMsgReply_DataChangesReplies.ProtoReflect.Descriptor instead.
func (*DataMsgReply_DataChangesReplies) Descriptor() ([]byte, []int) {
	return file_datamsg_proto_rawDescGZIP(), []int{3, 0}
}

func (x *DataMsgReply_DataChangesReplies) GetReplies() []*DataChangeReply {
	if x != nil {
		return x.Replies
	}
	return nil
}

type DataMsgReply_DataResyncsReplies struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Replies []*DataResyncReply `protobuf:"bytes,1,rep,name=replies,proto3" json:"replies,omitempty"`
}

func (x *DataMsgReply_DataResyncsReplies) Reset() {
	*x = DataMsgReply_DataResyncsReplies{}
	if protoimpl.UnsafeEnabled {
		mi := &file_datamsg_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DataMsgReply_DataResyncsReplies) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataMsgReply_DataResyncsReplies) ProtoMessage() {}

func (x *DataMsgReply_DataResyncsReplies) ProtoReflect() protoreflect.Message {
	mi := &file_datamsg_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataMsgReply_DataResyncsReplies.ProtoReflect.Descriptor instead.
func (*DataMsgReply_DataResyncsReplies) Descriptor() ([]byte, []int) {
	return file_datamsg_proto_rawDescGZIP(), []int{3, 1}
}

func (x *DataMsgReply_DataResyncsReplies) GetReplies() []*DataResyncReply {
	if x != nil {
		return x.Replies
	}
	return nil
}

var File_datamsg_proto protoreflect.FileDescriptor

var file_datamsg_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x64, 0x61, 0x74, 0x61, 0x6d, 0x73, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x03, 0x6d, 0x73, 0x67, 0x22, 0xc0, 0x01, 0x0a, 0x0e, 0x44, 0x61, 0x74, 0x61, 0x4d, 0x73, 0x67,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1e, 0x0a, 0x05, 0x6d, 0x73, 0x67, 0x49, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x08, 0x2e, 0x6d, 0x73, 0x67, 0x2e, 0x53, 0x65, 0x71,
	0x52, 0x05, 0x6d, 0x73, 0x67, 0x49, 0x64, 0x12, 0x1a, 0x0a, 0x03, 0x74, 0x78, 0x6e, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x08, 0x2e, 0x6d, 0x73, 0x67, 0x2e, 0x53, 0x65, 0x71, 0x52, 0x03,
	0x74, 0x78, 0x6e, 0x12, 0x38, 0x0a, 0x0b, 0x64, 0x61, 0x74, 0x61, 0x43, 0x68, 0x61, 0x6e, 0x67,
	0x65, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x6d, 0x73, 0x67, 0x2e, 0x44,
	0x61, 0x74, 0x61, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x52, 0x0b, 0x64, 0x61, 0x74, 0x61, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x73, 0x12, 0x38, 0x0a,
	0x0b, 0x64, 0x61, 0x74, 0x61, 0x52, 0x65, 0x73, 0x79, 0x6e, 0x63, 0x73, 0x18, 0x04, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x16, 0x2e, 0x6d, 0x73, 0x67, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x52, 0x65, 0x73,
	0x79, 0x6e, 0x63, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x52, 0x0b, 0x64, 0x61, 0x74, 0x61,
	0x52, 0x65, 0x73, 0x79, 0x6e, 0x63, 0x73, 0x22, 0x6e, 0x0a, 0x12, 0x44, 0x61, 0x74, 0x61, 0x52,
	0x65, 0x73, 0x79, 0x6e, 0x63, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x73, 0x12, 0x1e, 0x0a,
	0x05, 0x6d, 0x73, 0x67, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x08, 0x2e, 0x6d,
	0x73, 0x67, 0x2e, 0x53, 0x65, 0x71, 0x52, 0x05, 0x6d, 0x73, 0x67, 0x49, 0x64, 0x12, 0x38, 0x0a,
	0x0b, 0x64, 0x61, 0x74, 0x61, 0x52, 0x65, 0x73, 0x79, 0x6e, 0x63, 0x73, 0x18, 0x02, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x16, 0x2e, 0x6d, 0x73, 0x67, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x52, 0x65, 0x73,
	0x79, 0x6e, 0x63, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x52, 0x0b, 0x64, 0x61, 0x74, 0x61,
	0x52, 0x65, 0x73, 0x79, 0x6e, 0x63, 0x73, 0x22, 0xe8, 0x01, 0x0a, 0x11, 0x44, 0x61, 0x74, 0x61,
	0x52, 0x65, 0x73, 0x79, 0x6e, 0x63, 0x52, 0x65, 0x70, 0x6c, 0x69, 0x65, 0x73, 0x12, 0x1e, 0x0a,
	0x05, 0x6d, 0x73, 0x67, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x08, 0x2e, 0x6d,
	0x73, 0x67, 0x2e, 0x53, 0x65, 0x71, 0x52, 0x05, 0x6d, 0x73, 0x67, 0x49, 0x64, 0x12, 0x20, 0x0a,
	0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x6d,
	0x73, 0x67, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x12,
	0x4b, 0x0a, 0x0b, 0x64, 0x61, 0x74, 0x61, 0x52, 0x65, 0x73, 0x79, 0x6e, 0x63, 0x73, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x29, 0x2e, 0x6d, 0x73, 0x67, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x52,
	0x65, 0x73, 0x79, 0x6e, 0x63, 0x52, 0x65, 0x70, 0x6c, 0x69, 0x65, 0x73, 0x2e, 0x44, 0x61, 0x74,
	0x61, 0x52, 0x65, 0x73, 0x79, 0x6e, 0x63, 0x73, 0x52, 0x65, 0x70, 0x6c, 0x69, 0x65, 0x73, 0x52,
	0x0b, 0x64, 0x61, 0x74, 0x61, 0x52, 0x65, 0x73, 0x79, 0x6e, 0x63, 0x73, 0x1a, 0x44, 0x0a, 0x12,
	0x44, 0x61, 0x74, 0x61, 0x52, 0x65, 0x73, 0x79, 0x6e, 0x63, 0x73, 0x52, 0x65, 0x70, 0x6c, 0x69,
	0x65, 0x73, 0x12, 0x2e, 0x0a, 0x07, 0x72, 0x65, 0x70, 0x6c, 0x69, 0x65, 0x73, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x6d, 0x73, 0x67, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x52, 0x65,
	0x73, 0x79, 0x6e, 0x63, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x52, 0x07, 0x72, 0x65, 0x70, 0x6c, 0x69,
	0x65, 0x73, 0x22, 0xec, 0x02, 0x0a, 0x0c, 0x44, 0x61, 0x74, 0x61, 0x4d, 0x73, 0x67, 0x52, 0x65,
	0x70, 0x6c, 0x79, 0x12, 0x1e, 0x0a, 0x05, 0x6d, 0x73, 0x67, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x08, 0x2e, 0x6d, 0x73, 0x67, 0x2e, 0x53, 0x65, 0x71, 0x52, 0x05, 0x6d, 0x73,
	0x67, 0x49, 0x64, 0x12, 0x20, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x6d, 0x73, 0x67, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x52, 0x05,
	0x65, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x46, 0x0a, 0x0b, 0x64, 0x61, 0x74, 0x61, 0x43, 0x68, 0x61,
	0x6e, 0x67, 0x65, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x24, 0x2e, 0x6d, 0x73, 0x67,
	0x2e, 0x44, 0x61, 0x74, 0x61, 0x4d, 0x73, 0x67, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x2e, 0x44, 0x61,
	0x74, 0x61, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x73, 0x52, 0x65, 0x70, 0x6c, 0x69, 0x65, 0x73,
	0x52, 0x0b, 0x64, 0x61, 0x74, 0x61, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x73, 0x12, 0x46, 0x0a,
	0x0b, 0x64, 0x61, 0x74, 0x61, 0x52, 0x65, 0x73, 0x79, 0x6e, 0x63, 0x73, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x24, 0x2e, 0x6d, 0x73, 0x67, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x4d, 0x73, 0x67,
	0x52, 0x65, 0x70, 0x6c, 0x79, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x52, 0x65, 0x73, 0x79, 0x6e, 0x63,
	0x73, 0x52, 0x65, 0x70, 0x6c, 0x69, 0x65, 0x73, 0x52, 0x0b, 0x64, 0x61, 0x74, 0x61, 0x52, 0x65,
	0x73, 0x79, 0x6e, 0x63, 0x73, 0x1a, 0x44, 0x0a, 0x12, 0x44, 0x61, 0x74, 0x61, 0x43, 0x68, 0x61,
	0x6e, 0x67, 0x65, 0x73, 0x52, 0x65, 0x70, 0x6c, 0x69, 0x65, 0x73, 0x12, 0x2e, 0x0a, 0x07, 0x72,
	0x65, 0x70, 0x6c, 0x69, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x6d,
	0x73, 0x67, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x52, 0x65, 0x70,
	0x6c, 0x79, 0x52, 0x07, 0x72, 0x65, 0x70, 0x6c, 0x69, 0x65, 0x73, 0x1a, 0x44, 0x0a, 0x12, 0x44,
	0x61, 0x74, 0x61, 0x52, 0x65, 0x73, 0x79, 0x6e, 0x63, 0x73, 0x52, 0x65, 0x70, 0x6c, 0x69, 0x65,
	0x73, 0x12, 0x2e, 0x0a, 0x07, 0x72, 0x65, 0x70, 0x6c, 0x69, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x14, 0x2e, 0x6d, 0x73, 0x67, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x52, 0x65, 0x73,
	0x79, 0x6e, 0x63, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x52, 0x07, 0x72, 0x65, 0x70, 0x6c, 0x69, 0x65,
	0x73, 0x22, 0x95, 0x01, 0x0a, 0x11, 0x44, 0x61, 0x74, 0x61, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x31, 0x0a, 0x0d, 0x6f, 0x70, 0x65,
	0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e,
	0x32, 0x0b, 0x2e, 0x6d, 0x73, 0x67, 0x2e, 0x50, 0x75, 0x74, 0x44, 0x65, 0x6c, 0x52, 0x0d, 0x6f,
	0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x12, 0x18, 0x0a, 0x07,
	0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x63,
	0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x12, 0x21, 0x0a, 0x0c, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e,
	0x74, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x63, 0x6f,
	0x6e, 0x74, 0x65, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x22, 0x6e, 0x0a, 0x0f, 0x44, 0x61, 0x74,
	0x61, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x10, 0x0a, 0x03,
	0x6b, 0x65, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x31,
	0x0a, 0x0d, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0b, 0x2e, 0x6d, 0x73, 0x67, 0x2e, 0x50, 0x75, 0x74, 0x44,
	0x65, 0x6c, 0x52, 0x0d, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x79, 0x70,
	0x65, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0x62, 0x0a, 0x11, 0x44, 0x61, 0x74,
	0x61, 0x52, 0x65, 0x73, 0x79, 0x6e, 0x63, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10,
	0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79,
	0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0c, 0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x12, 0x21, 0x0a, 0x0c, 0x63, 0x6f,
	0x6e, 0x74, 0x65, 0x6e, 0x74, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0b, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x22, 0x61, 0x0a,
	0x0f, 0x44, 0x61, 0x74, 0x61, 0x52, 0x65, 0x73, 0x79, 0x6e, 0x63, 0x52, 0x65, 0x70, 0x6c, 0x79,
	0x12, 0x24, 0x0a, 0x08, 0x72, 0x65, 0x73, 0x79, 0x6e, 0x63, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x08, 0x2e, 0x6d, 0x73, 0x67, 0x2e, 0x53, 0x65, 0x71, 0x52, 0x08, 0x72, 0x65,
	0x73, 0x79, 0x6e, 0x63, 0x49, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75,
	0x6c, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74,
	0x22, 0x58, 0x0a, 0x14, 0x52, 0x65, 0x73, 0x79, 0x6e, 0x63, 0x4e, 0x65, 0x65, 0x64, 0x65, 0x64,
	0x43, 0x61, 0x6c, 0x6c, 0x62, 0x61, 0x63, 0x6b, 0x12, 0x1e, 0x0a, 0x05, 0x6d, 0x73, 0x67, 0x49,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x08, 0x2e, 0x6d, 0x73, 0x67, 0x2e, 0x53, 0x65,
	0x71, 0x52, 0x05, 0x6d, 0x73, 0x67, 0x49, 0x64, 0x12, 0x20, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f,
	0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x6d, 0x73, 0x67, 0x2e, 0x45, 0x72,
	0x72, 0x6f, 0x72, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x22, 0x5d, 0x0a, 0x03, 0x53, 0x65,
	0x71, 0x12, 0x1e, 0x0a, 0x0a, 0x6f, 0x72, 0x69, 0x67, 0x69, 0x6e, 0x61, 0x74, 0x6f, 0x72, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x6f, 0x72, 0x69, 0x67, 0x69, 0x6e, 0x61, 0x74, 0x6f,
	0x72, 0x12, 0x24, 0x0a, 0x0d, 0x73, 0x65, 0x71, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x53,
	0x65, 0x63, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0d, 0x73, 0x65, 0x71, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x64, 0x53, 0x65, 0x63, 0x12, 0x10, 0x0a, 0x03, 0x73, 0x65, 0x71, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x0d, 0x52, 0x03, 0x73, 0x65, 0x71, 0x22, 0x21, 0x0a, 0x05, 0x45, 0x72, 0x72,
	0x6f, 0x72, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x27, 0x0a, 0x0b,
	0x50, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x6d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x25, 0x0a, 0x09, 0x50, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x70,
	0x6c, 0x79, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2a, 0x1a, 0x0a, 0x06,
	0x50, 0x75, 0x74, 0x44, 0x65, 0x6c, 0x12, 0x07, 0x0a, 0x03, 0x50, 0x55, 0x54, 0x10, 0x00, 0x12,
	0x07, 0x0a, 0x03, 0x44, 0x45, 0x4c, 0x10, 0x01, 0x32, 0xc1, 0x01, 0x0a, 0x0e, 0x44, 0x61, 0x74,
	0x61, 0x4d, 0x73, 0x67, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x41, 0x0a, 0x0b, 0x64,
	0x61, 0x74, 0x61, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x73, 0x12, 0x16, 0x2e, 0x6d, 0x73, 0x67,
	0x2e, 0x44, 0x61, 0x74, 0x61, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x14, 0x2e, 0x6d, 0x73, 0x67, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x43, 0x68, 0x61,
	0x6e, 0x67, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x28, 0x01, 0x30, 0x01, 0x12, 0x40,
	0x0a, 0x0b, 0x64, 0x61, 0x74, 0x61, 0x52, 0x65, 0x73, 0x79, 0x6e, 0x63, 0x73, 0x12, 0x17, 0x2e,
	0x6d, 0x73, 0x67, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x52, 0x65, 0x73, 0x79, 0x6e, 0x63, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x73, 0x1a, 0x16, 0x2e, 0x6d, 0x73, 0x67, 0x2e, 0x44, 0x61, 0x74,
	0x61, 0x52, 0x65, 0x73, 0x79, 0x6e, 0x63, 0x52, 0x65, 0x70, 0x6c, 0x69, 0x65, 0x73, 0x22, 0x00,
	0x12, 0x2a, 0x0a, 0x04, 0x70, 0x69, 0x6e, 0x67, 0x12, 0x10, 0x2e, 0x6d, 0x73, 0x67, 0x2e, 0x50,
	0x69, 0x6e, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0e, 0x2e, 0x6d, 0x73, 0x67,
	0x2e, 0x50, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x42, 0x30, 0x5a, 0x2e,
	0x67, 0x6f, 0x2e, 0x6c, 0x69, 0x67, 0x61, 0x74, 0x6f, 0x2e, 0x69, 0x6f, 0x2f, 0x63, 0x6e, 0x2d,
	0x69, 0x6e, 0x66, 0x72, 0x61, 0x2f, 0x76, 0x32, 0x2f, 0x64, 0x61, 0x74, 0x61, 0x73, 0x79, 0x6e,
	0x63, 0x2f, 0x73, 0x79, 0x6e, 0x63, 0x62, 0x61, 0x73, 0x65, 0x2f, 0x6d, 0x73, 0x67, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_datamsg_proto_rawDescOnce sync.Once
	file_datamsg_proto_rawDescData = file_datamsg_proto_rawDesc
)

func file_datamsg_proto_rawDescGZIP() []byte {
	file_datamsg_proto_rawDescOnce.Do(func() {
		file_datamsg_proto_rawDescData = protoimpl.X.CompressGZIP(file_datamsg_proto_rawDescData)
	})
	return file_datamsg_proto_rawDescData
}

var file_datamsg_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_datamsg_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_datamsg_proto_goTypes = []interface{}{
	(PutDel)(0),                                  // 0: msg.PutDel
	(*DataMsgRequest)(nil),                       // 1: msg.DataMsgRequest
	(*DataResyncRequests)(nil),                   // 2: msg.DataResyncRequests
	(*DataResyncReplies)(nil),                    // 3: msg.DataResyncReplies
	(*DataMsgReply)(nil),                         // 4: msg.DataMsgReply
	(*DataChangeRequest)(nil),                    // 5: msg.DataChangeRequest
	(*DataChangeReply)(nil),                      // 6: msg.DataChangeReply
	(*DataResyncRequest)(nil),                    // 7: msg.DataResyncRequest
	(*DataResyncReply)(nil),                      // 8: msg.DataResyncReply
	(*ResyncNeededCallback)(nil),                 // 9: msg.ResyncNeededCallback
	(*Seq)(nil),                                  // 10: msg.Seq
	(*Error)(nil),                                // 11: msg.Error
	(*PingRequest)(nil),                          // 12: msg.PingRequest
	(*PingReply)(nil),                            // 13: msg.PingReply
	(*DataResyncReplies_DataResyncsReplies)(nil), // 14: msg.DataResyncReplies.DataResyncsReplies
	(*DataMsgReply_DataChangesReplies)(nil),      // 15: msg.DataMsgReply.DataChangesReplies
	(*DataMsgReply_DataResyncsReplies)(nil),      // 16: msg.DataMsgReply.DataResyncsReplies
}
var file_datamsg_proto_depIdxs = []int32{
	10, // 0: msg.DataMsgRequest.msgId:type_name -> msg.Seq
	10, // 1: msg.DataMsgRequest.txn:type_name -> msg.Seq
	5,  // 2: msg.DataMsgRequest.dataChanges:type_name -> msg.DataChangeRequest
	7,  // 3: msg.DataMsgRequest.dataResyncs:type_name -> msg.DataResyncRequest
	10, // 4: msg.DataResyncRequests.msgId:type_name -> msg.Seq
	7,  // 5: msg.DataResyncRequests.dataResyncs:type_name -> msg.DataResyncRequest
	10, // 6: msg.DataResyncReplies.msgId:type_name -> msg.Seq
	11, // 7: msg.DataResyncReplies.error:type_name -> msg.Error
	14, // 8: msg.DataResyncReplies.dataResyncs:type_name -> msg.DataResyncReplies.DataResyncsReplies
	10, // 9: msg.DataMsgReply.msgId:type_name -> msg.Seq
	11, // 10: msg.DataMsgReply.error:type_name -> msg.Error
	15, // 11: msg.DataMsgReply.dataChanges:type_name -> msg.DataMsgReply.DataChangesReplies
	16, // 12: msg.DataMsgReply.dataResyncs:type_name -> msg.DataMsgReply.DataResyncsReplies
	0,  // 13: msg.DataChangeRequest.operationType:type_name -> msg.PutDel
	0,  // 14: msg.DataChangeReply.operationType:type_name -> msg.PutDel
	10, // 15: msg.DataResyncReply.resyncId:type_name -> msg.Seq
	10, // 16: msg.ResyncNeededCallback.msgId:type_name -> msg.Seq
	11, // 17: msg.ResyncNeededCallback.error:type_name -> msg.Error
	8,  // 18: msg.DataResyncReplies.DataResyncsReplies.replies:type_name -> msg.DataResyncReply
	6,  // 19: msg.DataMsgReply.DataChangesReplies.replies:type_name -> msg.DataChangeReply
	8,  // 20: msg.DataMsgReply.DataResyncsReplies.replies:type_name -> msg.DataResyncReply
	5,  // 21: msg.DataMsgService.dataChanges:input_type -> msg.DataChangeRequest
	2,  // 22: msg.DataMsgService.dataResyncs:input_type -> msg.DataResyncRequests
	12, // 23: msg.DataMsgService.ping:input_type -> msg.PingRequest
	6,  // 24: msg.DataMsgService.dataChanges:output_type -> msg.DataChangeReply
	3,  // 25: msg.DataMsgService.dataResyncs:output_type -> msg.DataResyncReplies
	13, // 26: msg.DataMsgService.ping:output_type -> msg.PingReply
	24, // [24:27] is the sub-list for method output_type
	21, // [21:24] is the sub-list for method input_type
	21, // [21:21] is the sub-list for extension type_name
	21, // [21:21] is the sub-list for extension extendee
	0,  // [0:21] is the sub-list for field type_name
}

func init() { file_datamsg_proto_init() }
func file_datamsg_proto_init() {
	if File_datamsg_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_datamsg_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DataMsgRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_datamsg_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DataResyncRequests); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_datamsg_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DataResyncReplies); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_datamsg_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DataMsgReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_datamsg_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DataChangeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_datamsg_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DataChangeReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_datamsg_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DataResyncRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_datamsg_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DataResyncReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_datamsg_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResyncNeededCallback); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_datamsg_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Seq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_datamsg_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Error); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_datamsg_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PingRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_datamsg_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PingReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_datamsg_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DataResyncReplies_DataResyncsReplies); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_datamsg_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DataMsgReply_DataChangesReplies); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_datamsg_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DataMsgReply_DataResyncsReplies); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_datamsg_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_datamsg_proto_goTypes,
		DependencyIndexes: file_datamsg_proto_depIdxs,
		EnumInfos:         file_datamsg_proto_enumTypes,
		MessageInfos:      file_datamsg_proto_msgTypes,
	}.Build()
	File_datamsg_proto = out.File
	file_datamsg_proto_rawDesc = nil
	file_datamsg_proto_goTypes = nil
	file_datamsg_proto_depIdxs = nil
}
