// Code generated by protoc-gen-go. DO NOT EDIT.
// source: accesssecurity.proto

// Package access_security provides basic definition of user and permission group

package access_security

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type User struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	Permissions          []string `protobuf:"bytes,3,rep,name=permissions,proto3" json:"permissions,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_6bb83253976cb388, []int{0}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *User) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *User) GetPermissions() []string {
	if m != nil {
		return m.Permissions
	}
	return nil
}

type PermissionGroup struct {
	Name                 string                         `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Permissions          []*PermissionGroup_Permissions `protobuf:"bytes,2,rep,name=permissions,proto3" json:"permissions,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                       `json:"-"`
	XXX_unrecognized     []byte                         `json:"-"`
	XXX_sizecache        int32                          `json:"-"`
}

func (m *PermissionGroup) Reset()         { *m = PermissionGroup{} }
func (m *PermissionGroup) String() string { return proto.CompactTextString(m) }
func (*PermissionGroup) ProtoMessage()    {}
func (*PermissionGroup) Descriptor() ([]byte, []int) {
	return fileDescriptor_6bb83253976cb388, []int{1}
}

func (m *PermissionGroup) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PermissionGroup.Unmarshal(m, b)
}
func (m *PermissionGroup) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PermissionGroup.Marshal(b, m, deterministic)
}
func (m *PermissionGroup) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PermissionGroup.Merge(m, src)
}
func (m *PermissionGroup) XXX_Size() int {
	return xxx_messageInfo_PermissionGroup.Size(m)
}
func (m *PermissionGroup) XXX_DiscardUnknown() {
	xxx_messageInfo_PermissionGroup.DiscardUnknown(m)
}

var xxx_messageInfo_PermissionGroup proto.InternalMessageInfo

func (m *PermissionGroup) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *PermissionGroup) GetPermissions() []*PermissionGroup_Permissions {
	if m != nil {
		return m.Permissions
	}
	return nil
}

type PermissionGroup_Permissions struct {
	Url                  string   `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	AllowedMethods       []string `protobuf:"bytes,2,rep,name=allowed_methods,json=allowedMethods,proto3" json:"allowed_methods,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PermissionGroup_Permissions) Reset()         { *m = PermissionGroup_Permissions{} }
func (m *PermissionGroup_Permissions) String() string { return proto.CompactTextString(m) }
func (*PermissionGroup_Permissions) ProtoMessage()    {}
func (*PermissionGroup_Permissions) Descriptor() ([]byte, []int) {
	return fileDescriptor_6bb83253976cb388, []int{1, 0}
}

func (m *PermissionGroup_Permissions) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PermissionGroup_Permissions.Unmarshal(m, b)
}
func (m *PermissionGroup_Permissions) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PermissionGroup_Permissions.Marshal(b, m, deterministic)
}
func (m *PermissionGroup_Permissions) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PermissionGroup_Permissions.Merge(m, src)
}
func (m *PermissionGroup_Permissions) XXX_Size() int {
	return xxx_messageInfo_PermissionGroup_Permissions.Size(m)
}
func (m *PermissionGroup_Permissions) XXX_DiscardUnknown() {
	xxx_messageInfo_PermissionGroup_Permissions.DiscardUnknown(m)
}

var xxx_messageInfo_PermissionGroup_Permissions proto.InternalMessageInfo

func (m *PermissionGroup_Permissions) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *PermissionGroup_Permissions) GetAllowedMethods() []string {
	if m != nil {
		return m.AllowedMethods
	}
	return nil
}

func init() {
	proto.RegisterType((*User)(nil), "access_security.User")
	proto.RegisterType((*PermissionGroup)(nil), "access_security.PermissionGroup")
	proto.RegisterType((*PermissionGroup_Permissions)(nil), "access_security.PermissionGroup.Permissions")
}

func init() { proto.RegisterFile("accesssecurity.proto", fileDescriptor_6bb83253976cb388) }

var fileDescriptor_6bb83253976cb388 = []byte{
	// 207 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x49, 0x4c, 0x4e, 0x4e,
	0x2d, 0x2e, 0x2e, 0x4e, 0x4d, 0x2e, 0x2d, 0xca, 0x2c, 0xa9, 0xd4, 0x2b, 0x28, 0xca, 0x2f, 0xc9,
	0x17, 0xe2, 0x87, 0x88, 0xc6, 0xc3, 0x84, 0x95, 0x22, 0xb8, 0x58, 0x42, 0x8b, 0x53, 0x8b, 0x84,
	0x84, 0xb8, 0x58, 0xf2, 0x12, 0x73, 0x53, 0x25, 0x18, 0x15, 0x18, 0x35, 0x38, 0x83, 0xc0, 0x6c,
	0x21, 0x29, 0x2e, 0x8e, 0x82, 0xc4, 0xe2, 0xe2, 0xf2, 0xfc, 0xa2, 0x14, 0x09, 0x26, 0xb0, 0x38,
	0x9c, 0x2f, 0xa4, 0xc0, 0xc5, 0x5d, 0x90, 0x5a, 0x94, 0x9b, 0x59, 0x5c, 0x9c, 0x99, 0x9f, 0x57,
	0x2c, 0xc1, 0xac, 0xc0, 0xac, 0xc1, 0x19, 0x84, 0x2c, 0xa4, 0xb4, 0x9f, 0x91, 0x8b, 0x3f, 0x00,
	0xce, 0x77, 0x2f, 0xca, 0x2f, 0x2d, 0xc0, 0x6a, 0x8b, 0x1f, 0xaa, 0x49, 0x4c, 0x0a, 0xcc, 0x1a,
	0xdc, 0x46, 0x3a, 0x7a, 0x68, 0x0e, 0xd5, 0x43, 0x33, 0x0a, 0x89, 0x5f, 0x8c, 0x62, 0xaf, 0x94,
	0x07, 0x17, 0x37, 0x92, 0x9c, 0x90, 0x00, 0x17, 0x73, 0x69, 0x51, 0x0e, 0xd4, 0x46, 0x10, 0x53,
	0x48, 0x9d, 0x8b, 0x3f, 0x31, 0x27, 0x27, 0xbf, 0x3c, 0x35, 0x25, 0x3e, 0x37, 0xb5, 0x24, 0x23,
	0x3f, 0x05, 0x62, 0x29, 0x67, 0x10, 0x1f, 0x54, 0xd8, 0x17, 0x22, 0x9a, 0xc4, 0x06, 0x0e, 0x33,
	0x63, 0x40, 0x00, 0x00, 0x00, 0xff, 0xff, 0x93, 0x69, 0x99, 0xc5, 0x4b, 0x01, 0x00, 0x00,
}
