---
dist: trusty
sudo: required

language: go
go:
  - 1.x

go_import_path: go.ligato.io/cn-infra/v2

addons:
  apt:
    packages:
      - npm

git:
  depth: 1

before_install:
  - make get-linkcheck
  - make get-yamllint

install:
  - make dep-check
  - make check-links || true
  - make yamllint

before_script:
  - make get-linter
  - make get-testtools
  - go get -v github.com/mattn/goveralls

script:
  - make lint
  - make build
  - make test-cover

after_success:
  - goveralls -coverprofile=/tmp/coverage.out -service=travis-ci

notifications:
  slack:
    rooms:
      - ligato:QNOK2VgHH6k40T8nQxmSgRmo
    on_success: change
    on_failure: always
