// Code generated by protoc-gen-go. DO NOT EDIT.
// source: process.proto

// Package process provides a data model for process manager plugin template

package process

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Template struct {
	Name                 string            `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Cmd                  string            `protobuf:"bytes,2,opt,name=cmd,proto3" json:"cmd,omitempty"`
	POptions             *TemplatePOptions `protobuf:"bytes,3,opt,name=p_options,json=pOptions,proto3" json:"p_options,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Template) Reset()         { *m = Template{} }
func (m *Template) String() string { return proto.CompactTextString(m) }
func (*Template) ProtoMessage()    {}
func (*Template) Descriptor() ([]byte, []int) {
	return fileDescriptor_54c4d0e8c0aaf5c3, []int{0}
}

func (m *Template) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Template.Unmarshal(m, b)
}
func (m *Template) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Template.Marshal(b, m, deterministic)
}
func (m *Template) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Template.Merge(m, src)
}
func (m *Template) XXX_Size() int {
	return xxx_messageInfo_Template.Size(m)
}
func (m *Template) XXX_DiscardUnknown() {
	xxx_messageInfo_Template.DiscardUnknown(m)
}

var xxx_messageInfo_Template proto.InternalMessageInfo

func (m *Template) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Template) GetCmd() string {
	if m != nil {
		return m.Cmd
	}
	return ""
}

func (m *Template) GetPOptions() *TemplatePOptions {
	if m != nil {
		return m.POptions
	}
	return nil
}

type TemplatePOptions struct {
	Args                 []string `protobuf:"bytes,1,rep,name=args,proto3" json:"args,omitempty"`
	OutWriter            bool     `protobuf:"varint,2,opt,name=out_writer,json=outWriter,proto3" json:"out_writer,omitempty"`
	ErrWriter            bool     `protobuf:"varint,3,opt,name=err_writer,json=errWriter,proto3" json:"err_writer,omitempty"`
	Restart              int32    `protobuf:"varint,4,opt,name=restart,proto3" json:"restart,omitempty"`
	Detach               bool     `protobuf:"varint,5,opt,name=detach,proto3" json:"detach,omitempty"`
	RunOnStartup         bool     `protobuf:"varint,6,opt,name=run_on_startup,json=runOnStartup,proto3" json:"run_on_startup,omitempty"`
	Notify               bool     `protobuf:"varint,7,opt,name=notify,proto3" json:"notify,omitempty"`
	AutoTerminate        bool     `protobuf:"varint,8,opt,name=auto_terminate,json=autoTerminate,proto3" json:"auto_terminate,omitempty"`
	CpuAffinity          string   `protobuf:"bytes,9,opt,name=cpu_affinity,json=cpuAffinity,proto3" json:"cpu_affinity,omitempty"`
	CpuAffinityList      string   `protobuf:"bytes,11,opt,name=cpu_affinity_list,json=cpuAffinityList,proto3" json:"cpu_affinity_list,omitempty"`
	CpuAffinityDelay     string   `protobuf:"bytes,10,opt,name=cpu_affinity_delay,json=cpuAffinityDelay,proto3" json:"cpu_affinity_delay,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TemplatePOptions) Reset()         { *m = TemplatePOptions{} }
func (m *TemplatePOptions) String() string { return proto.CompactTextString(m) }
func (*TemplatePOptions) ProtoMessage()    {}
func (*TemplatePOptions) Descriptor() ([]byte, []int) {
	return fileDescriptor_54c4d0e8c0aaf5c3, []int{0, 0}
}

func (m *TemplatePOptions) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TemplatePOptions.Unmarshal(m, b)
}
func (m *TemplatePOptions) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TemplatePOptions.Marshal(b, m, deterministic)
}
func (m *TemplatePOptions) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TemplatePOptions.Merge(m, src)
}
func (m *TemplatePOptions) XXX_Size() int {
	return xxx_messageInfo_TemplatePOptions.Size(m)
}
func (m *TemplatePOptions) XXX_DiscardUnknown() {
	xxx_messageInfo_TemplatePOptions.DiscardUnknown(m)
}

var xxx_messageInfo_TemplatePOptions proto.InternalMessageInfo

func (m *TemplatePOptions) GetArgs() []string {
	if m != nil {
		return m.Args
	}
	return nil
}

func (m *TemplatePOptions) GetOutWriter() bool {
	if m != nil {
		return m.OutWriter
	}
	return false
}

func (m *TemplatePOptions) GetErrWriter() bool {
	if m != nil {
		return m.ErrWriter
	}
	return false
}

func (m *TemplatePOptions) GetRestart() int32 {
	if m != nil {
		return m.Restart
	}
	return 0
}

func (m *TemplatePOptions) GetDetach() bool {
	if m != nil {
		return m.Detach
	}
	return false
}

func (m *TemplatePOptions) GetRunOnStartup() bool {
	if m != nil {
		return m.RunOnStartup
	}
	return false
}

func (m *TemplatePOptions) GetNotify() bool {
	if m != nil {
		return m.Notify
	}
	return false
}

func (m *TemplatePOptions) GetAutoTerminate() bool {
	if m != nil {
		return m.AutoTerminate
	}
	return false
}

func (m *TemplatePOptions) GetCpuAffinity() string {
	if m != nil {
		return m.CpuAffinity
	}
	return ""
}

func (m *TemplatePOptions) GetCpuAffinityList() string {
	if m != nil {
		return m.CpuAffinityList
	}
	return ""
}

func (m *TemplatePOptions) GetCpuAffinityDelay() string {
	if m != nil {
		return m.CpuAffinityDelay
	}
	return ""
}

func init() {
	proto.RegisterType((*Template)(nil), "process.Template")
	proto.RegisterType((*TemplatePOptions)(nil), "process.Template.pOptions")
}

func init() { proto.RegisterFile("process.proto", fileDescriptor_54c4d0e8c0aaf5c3) }

var fileDescriptor_54c4d0e8c0aaf5c3 = []byte{
	// 327 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x91, 0xcd, 0x6a, 0xe3, 0x30,
	0x10, 0xc7, 0x71, 0x9c, 0x0f, 0x7b, 0xf2, 0xb1, 0x59, 0x1d, 0x16, 0x11, 0x58, 0xf0, 0x2e, 0x2d,
	0x84, 0x52, 0x72, 0x68, 0x0f, 0x3d, 0x17, 0x7a, 0x2c, 0x04, 0xdc, 0x40, 0x8f, 0x46, 0x75, 0x94,
	0x56, 0x10, 0x4b, 0x62, 0x34, 0xa2, 0xe4, 0x5d, 0xfb, 0x10, 0x7d, 0x84, 0x22, 0xd9, 0x2e, 0xe9,
	0xed, 0xff, 0xf1, 0x9b, 0x19, 0x90, 0x60, 0x6e, 0xd1, 0xd4, 0xd2, 0xb9, 0x8d, 0x45, 0x43, 0x86,
	0x4d, 0x3a, 0xfb, 0xff, 0x23, 0x85, 0x6c, 0x27, 0x1b, 0x7b, 0x14, 0x24, 0x19, 0x83, 0xa1, 0x16,
	0x8d, 0xe4, 0x49, 0x91, 0xac, 0xf3, 0x32, 0x6a, 0xb6, 0x84, 0xb4, 0x6e, 0xf6, 0x7c, 0x10, 0xa3,
	0x20, 0xd9, 0x1d, 0xe4, 0xb6, 0x32, 0x96, 0x94, 0xd1, 0x8e, 0xa7, 0x45, 0xb2, 0x9e, 0xde, 0xac,
	0x36, 0xfd, 0xfa, 0x7e, 0xd7, 0xc6, 0x6e, 0x5b, 0xa2, 0xcc, 0x7a, 0xb5, 0xfa, 0x1c, 0xc0, 0xb7,
	0x09, 0xb7, 0x04, 0xbe, 0x3a, 0x9e, 0x14, 0x69, 0xb8, 0x15, 0x34, 0xfb, 0x0b, 0x60, 0x3c, 0x55,
	0xef, 0xa8, 0x48, 0x62, 0x3c, 0x99, 0x95, 0xb9, 0xf1, 0xf4, 0x1c, 0x83, 0x50, 0x4b, 0xc4, 0xbe,
	0x4e, 0xdb, 0x5a, 0x22, 0x76, 0x35, 0x87, 0x09, 0x4a, 0x47, 0x02, 0x89, 0x0f, 0x8b, 0x64, 0x3d,
	0x2a, 0x7b, 0xcb, 0xfe, 0xc0, 0x78, 0x2f, 0x49, 0xd4, 0x6f, 0x7c, 0x14, 0x87, 0x3a, 0xc7, 0x2e,
	0x60, 0x81, 0x5e, 0x57, 0x46, 0x57, 0x91, 0xf3, 0x96, 0x8f, 0x63, 0x3f, 0x43, 0xaf, 0xb7, 0xfa,
	0xa9, 0xcd, 0xc2, 0xb4, 0x36, 0xa4, 0x0e, 0x27, 0x3e, 0x69, 0xa7, 0x5b, 0xc7, 0x2e, 0x61, 0x21,
	0x3c, 0x99, 0x8a, 0x24, 0x36, 0x4a, 0x0b, 0x92, 0x3c, 0x8b, 0xfd, 0x3c, 0xa4, 0xbb, 0x3e, 0x64,
	0xff, 0x60, 0x56, 0x5b, 0x5f, 0x89, 0xc3, 0x41, 0x69, 0x45, 0x27, 0x9e, 0xc7, 0x97, 0x9c, 0xd6,
	0xd6, 0xdf, 0x77, 0x11, 0xbb, 0x82, 0xdf, 0xe7, 0x48, 0x75, 0x54, 0x8e, 0xf8, 0x34, 0x72, 0xbf,
	0xce, 0xb8, 0x47, 0xe5, 0x88, 0x5d, 0x03, 0xfb, 0xc1, 0xee, 0xe5, 0x51, 0x9c, 0x38, 0x44, 0x78,
	0x79, 0x06, 0x3f, 0x84, 0xfc, 0x65, 0x1c, 0xbf, 0xfb, 0xf6, 0x2b, 0x00, 0x00, 0xff, 0xff, 0x0a,
	0xcc, 0x6c, 0x7d, 0xff, 0x01, 0x00, 0x00,
}
