// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.17.3
// source: model/process/process.proto

// Package process provides a data model for process manager plugin template

package process

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Template struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name     string            `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"` // Serves as a filename for given template
	Cmd      string            `protobuf:"bytes,2,opt,name=cmd,proto3" json:"cmd,omitempty"`   // Process command
	POptions *TemplatePOptions `protobuf:"bytes,3,opt,name=p_options,json=pOptions,proto3" json:"p_options,omitempty"`
}

func (x *Template) Reset() {
	*x = Template{}
	if protoimpl.UnsafeEnabled {
		mi := &file_model_process_process_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Template) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Template) ProtoMessage() {}

func (x *Template) ProtoReflect() protoreflect.Message {
	mi := &file_model_process_process_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Template.ProtoReflect.Descriptor instead.
func (*Template) Descriptor() ([]byte, []int) {
	return file_model_process_process_proto_rawDescGZIP(), []int{0}
}

func (x *Template) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Template) GetCmd() string {
	if x != nil {
		return x.Cmd
	}
	return ""
}

func (x *Template) GetPOptions() *TemplatePOptions {
	if x != nil {
		return x.POptions
	}
	return nil
}

type TemplatePOptions struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Args             []string `protobuf:"bytes,1,rep,name=args,proto3" json:"args,omitempty"`                                        // Arguments process will be started with
	OutWriter        bool     `protobuf:"varint,2,opt,name=out_writer,json=outWriter,proto3" json:"out_writer,omitempty"`            // Use output writer. Note: only os.StdOut can be used this way
	ErrWriter        bool     `protobuf:"varint,3,opt,name=err_writer,json=errWriter,proto3" json:"err_writer,omitempty"`            // Use error writer. Note: only os.StdErr can be used this way
	Restart          int32    `protobuf:"varint,4,opt,name=restart,proto3" json:"restart,omitempty"`                                 // Number of automatic restarts, <0> means no restart, <-1> always restart
	Detach           bool     `protobuf:"varint,5,opt,name=detach,proto3" json:"detach,omitempty"`                                   // Set to true if process should be detached from parent application on startup
	RunOnStartup     bool     `protobuf:"varint,6,opt,name=run_on_startup,json=runOnStartup,proto3" json:"run_on_startup,omitempty"` // Set to true if process is expected to start right after plugin initialization
	Notify           bool     `protobuf:"varint,7,opt,name=notify,proto3" json:"notify,omitempty"`
	AutoTerminate    bool     `protobuf:"varint,8,opt,name=auto_terminate,json=autoTerminate,proto3" json:"auto_terminate,omitempty"`
	CpuAffinityMask  string   `protobuf:"bytes,9,opt,name=cpu_affinity_mask,json=cpuAffinityMask,proto3" json:"cpu_affinity_mask,omitempty"`
	CpuAffinityList  string   `protobuf:"bytes,10,opt,name=cpu_affinity_list,json=cpuAffinityList,proto3" json:"cpu_affinity_list,omitempty"`
	CpuAffinityDelay string   `protobuf:"bytes,11,opt,name=cpu_affinity_delay,json=cpuAffinityDelay,proto3" json:"cpu_affinity_delay,omitempty"` // Postpone CPU affinity setup if needed
}

func (x *TemplatePOptions) Reset() {
	*x = TemplatePOptions{}
	if protoimpl.UnsafeEnabled {
		mi := &file_model_process_process_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TemplatePOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TemplatePOptions) ProtoMessage() {}

func (x *TemplatePOptions) ProtoReflect() protoreflect.Message {
	mi := &file_model_process_process_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TemplatePOptions.ProtoReflect.Descriptor instead.
func (*TemplatePOptions) Descriptor() ([]byte, []int) {
	return file_model_process_process_proto_rawDescGZIP(), []int{0, 0}
}

func (x *TemplatePOptions) GetArgs() []string {
	if x != nil {
		return x.Args
	}
	return nil
}

func (x *TemplatePOptions) GetOutWriter() bool {
	if x != nil {
		return x.OutWriter
	}
	return false
}

func (x *TemplatePOptions) GetErrWriter() bool {
	if x != nil {
		return x.ErrWriter
	}
	return false
}

func (x *TemplatePOptions) GetRestart() int32 {
	if x != nil {
		return x.Restart
	}
	return 0
}

func (x *TemplatePOptions) GetDetach() bool {
	if x != nil {
		return x.Detach
	}
	return false
}

func (x *TemplatePOptions) GetRunOnStartup() bool {
	if x != nil {
		return x.RunOnStartup
	}
	return false
}

func (x *TemplatePOptions) GetNotify() bool {
	if x != nil {
		return x.Notify
	}
	return false
}

func (x *TemplatePOptions) GetAutoTerminate() bool {
	if x != nil {
		return x.AutoTerminate
	}
	return false
}

func (x *TemplatePOptions) GetCpuAffinityMask() string {
	if x != nil {
		return x.CpuAffinityMask
	}
	return ""
}

func (x *TemplatePOptions) GetCpuAffinityList() string {
	if x != nil {
		return x.CpuAffinityList
	}
	return ""
}

func (x *TemplatePOptions) GetCpuAffinityDelay() string {
	if x != nil {
		return x.CpuAffinityDelay
	}
	return ""
}

var File_model_process_process_proto protoreflect.FileDescriptor

var file_model_process_process_proto_rawDesc = []byte{
	0x0a, 0x1b, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2f, 0x70, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x2f,
	0x70, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x70,
	0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x22, 0xe5, 0x03, 0x0a, 0x08, 0x54, 0x65, 0x6d, 0x70, 0x6c,
	0x61, 0x74, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x63, 0x6d, 0x64, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x63, 0x6d, 0x64, 0x12, 0x37, 0x0a, 0x09, 0x70, 0x5f, 0x6f,
	0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x70,
	0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x2e, 0x54, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x2e,
	0x70, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x52, 0x08, 0x70, 0x4f, 0x70, 0x74, 0x69, 0x6f,
	0x6e, 0x73, 0x1a, 0xf9, 0x02, 0x0a, 0x08, 0x70, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12,
	0x12, 0x0a, 0x04, 0x61, 0x72, 0x67, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x04, 0x61,
	0x72, 0x67, 0x73, 0x12, 0x1d, 0x0a, 0x0a, 0x6f, 0x75, 0x74, 0x5f, 0x77, 0x72, 0x69, 0x74, 0x65,
	0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x09, 0x6f, 0x75, 0x74, 0x57, 0x72, 0x69, 0x74,
	0x65, 0x72, 0x12, 0x1d, 0x0a, 0x0a, 0x65, 0x72, 0x72, 0x5f, 0x77, 0x72, 0x69, 0x74, 0x65, 0x72,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x09, 0x65, 0x72, 0x72, 0x57, 0x72, 0x69, 0x74, 0x65,
	0x72, 0x12, 0x18, 0x0a, 0x07, 0x72, 0x65, 0x73, 0x74, 0x61, 0x72, 0x74, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x07, 0x72, 0x65, 0x73, 0x74, 0x61, 0x72, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x64,
	0x65, 0x74, 0x61, 0x63, 0x68, 0x18, 0x05, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x64, 0x65, 0x74,
	0x61, 0x63, 0x68, 0x12, 0x24, 0x0a, 0x0e, 0x72, 0x75, 0x6e, 0x5f, 0x6f, 0x6e, 0x5f, 0x73, 0x74,
	0x61, 0x72, 0x74, 0x75, 0x70, 0x18, 0x06, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0c, 0x72, 0x75, 0x6e,
	0x4f, 0x6e, 0x53, 0x74, 0x61, 0x72, 0x74, 0x75, 0x70, 0x12, 0x16, 0x0a, 0x06, 0x6e, 0x6f, 0x74,
	0x69, 0x66, 0x79, 0x18, 0x07, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x6e, 0x6f, 0x74, 0x69, 0x66,
	0x79, 0x12, 0x25, 0x0a, 0x0e, 0x61, 0x75, 0x74, 0x6f, 0x5f, 0x74, 0x65, 0x72, 0x6d, 0x69, 0x6e,
	0x61, 0x74, 0x65, 0x18, 0x08, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0d, 0x61, 0x75, 0x74, 0x6f, 0x54,
	0x65, 0x72, 0x6d, 0x69, 0x6e, 0x61, 0x74, 0x65, 0x12, 0x2a, 0x0a, 0x11, 0x63, 0x70, 0x75, 0x5f,
	0x61, 0x66, 0x66, 0x69, 0x6e, 0x69, 0x74, 0x79, 0x5f, 0x6d, 0x61, 0x73, 0x6b, 0x18, 0x09, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0f, 0x63, 0x70, 0x75, 0x41, 0x66, 0x66, 0x69, 0x6e, 0x69, 0x74, 0x79,
	0x4d, 0x61, 0x73, 0x6b, 0x12, 0x2a, 0x0a, 0x11, 0x63, 0x70, 0x75, 0x5f, 0x61, 0x66, 0x66, 0x69,
	0x6e, 0x69, 0x74, 0x79, 0x5f, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0f, 0x63, 0x70, 0x75, 0x41, 0x66, 0x66, 0x69, 0x6e, 0x69, 0x74, 0x79, 0x4c, 0x69, 0x73, 0x74,
	0x12, 0x2c, 0x0a, 0x12, 0x63, 0x70, 0x75, 0x5f, 0x61, 0x66, 0x66, 0x69, 0x6e, 0x69, 0x74, 0x79,
	0x5f, 0x64, 0x65, 0x6c, 0x61, 0x79, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x09, 0x52, 0x10, 0x63, 0x70,
	0x75, 0x41, 0x66, 0x66, 0x69, 0x6e, 0x69, 0x74, 0x79, 0x44, 0x65, 0x6c, 0x61, 0x79, 0x42, 0x45,
	0x5a, 0x43, 0x67, 0x6f, 0x2e, 0x6c, 0x69, 0x67, 0x61, 0x74, 0x6f, 0x2e, 0x69, 0x6f, 0x2f, 0x63,
	0x6e, 0x2d, 0x69, 0x6e, 0x66, 0x72, 0x61, 0x2f, 0x76, 0x32, 0x2f, 0x65, 0x78, 0x65, 0x63, 0x2f,
	0x70, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x2f, 0x74,
	0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x2f, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2f, 0x70, 0x72,
	0x6f, 0x63, 0x65, 0x73, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_model_process_process_proto_rawDescOnce sync.Once
	file_model_process_process_proto_rawDescData = file_model_process_process_proto_rawDesc
)

func file_model_process_process_proto_rawDescGZIP() []byte {
	file_model_process_process_proto_rawDescOnce.Do(func() {
		file_model_process_process_proto_rawDescData = protoimpl.X.CompressGZIP(file_model_process_process_proto_rawDescData)
	})
	return file_model_process_process_proto_rawDescData
}

var file_model_process_process_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_model_process_process_proto_goTypes = []interface{}{
	(*Template)(nil),         // 0: process.Template
	(*TemplatePOptions)(nil), // 1: process.Template.pOptions
}
var file_model_process_process_proto_depIdxs = []int32{
	1, // 0: process.Template.p_options:type_name -> process.Template.pOptions
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_model_process_process_proto_init() }
func file_model_process_process_proto_init() {
	if File_model_process_process_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_model_process_process_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Template); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_model_process_process_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TemplatePOptions); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_model_process_process_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_model_process_process_proto_goTypes,
		DependencyIndexes: file_model_process_process_proto_depIdxs,
		MessageInfos:      file_model_process_process_proto_msgTypes,
	}.Build()
	File_model_process_process_proto = out.File
	file_model_process_process_proto_rawDesc = nil
	file_model_process_process_proto_goTypes = nil
	file_model_process_process_proto_depIdxs = nil
}
