// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: apitrace.proto

package apitrace

/*
Package apitrace provides data model for binary API trace informations.
*/

import proto "github.com/gogo/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

type Trace struct {
	TracedEntries        []*Trace_TracedEntry `protobuf:"bytes,1,rep,name=traced_entries,json=tracedEntries" json:"traced_entries,omitempty"`
	AverageTimes         []*Trace_Average     `protobuf:"bytes,2,rep,name=average_times,json=averageTimes" json:"average_times,omitempty"`
	Overall              string               `protobuf:"bytes,3,opt,name=overall,proto3" json:"overall,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Trace) Reset()         { *m = Trace{} }
func (m *Trace) String() string { return proto.CompactTextString(m) }
func (*Trace) ProtoMessage()    {}
func (*Trace) Descriptor() ([]byte, []int) {
	return fileDescriptor_apitrace_cc9008d971ab8114, []int{0}
}
func (m *Trace) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Trace.Unmarshal(m, b)
}
func (m *Trace) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Trace.Marshal(b, m, deterministic)
}
func (dst *Trace) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Trace.Merge(dst, src)
}
func (m *Trace) XXX_Size() int {
	return xxx_messageInfo_Trace.Size(m)
}
func (m *Trace) XXX_DiscardUnknown() {
	xxx_messageInfo_Trace.DiscardUnknown(m)
}

var xxx_messageInfo_Trace proto.InternalMessageInfo

func (m *Trace) GetTracedEntries() []*Trace_TracedEntry {
	if m != nil {
		return m.TracedEntries
	}
	return nil
}

func (m *Trace) GetAverageTimes() []*Trace_Average {
	if m != nil {
		return m.AverageTimes
	}
	return nil
}

func (m *Trace) GetOverall() string {
	if m != nil {
		return m.Overall
	}
	return ""
}

type Trace_TracedEntry struct {
	Index                uint32   `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	MsgName              string   `protobuf:"bytes,2,opt,name=msg_name,json=msgName,proto3" json:"msg_name,omitempty"`
	Duration             string   `protobuf:"bytes,3,opt,name=duration,proto3" json:"duration,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Trace_TracedEntry) Reset()         { *m = Trace_TracedEntry{} }
func (m *Trace_TracedEntry) String() string { return proto.CompactTextString(m) }
func (*Trace_TracedEntry) ProtoMessage()    {}
func (*Trace_TracedEntry) Descriptor() ([]byte, []int) {
	return fileDescriptor_apitrace_cc9008d971ab8114, []int{0, 0}
}
func (m *Trace_TracedEntry) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Trace_TracedEntry.Unmarshal(m, b)
}
func (m *Trace_TracedEntry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Trace_TracedEntry.Marshal(b, m, deterministic)
}
func (dst *Trace_TracedEntry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Trace_TracedEntry.Merge(dst, src)
}
func (m *Trace_TracedEntry) XXX_Size() int {
	return xxx_messageInfo_Trace_TracedEntry.Size(m)
}
func (m *Trace_TracedEntry) XXX_DiscardUnknown() {
	xxx_messageInfo_Trace_TracedEntry.DiscardUnknown(m)
}

var xxx_messageInfo_Trace_TracedEntry proto.InternalMessageInfo

func (m *Trace_TracedEntry) GetIndex() uint32 {
	if m != nil {
		return m.Index
	}
	return 0
}

func (m *Trace_TracedEntry) GetMsgName() string {
	if m != nil {
		return m.MsgName
	}
	return ""
}

func (m *Trace_TracedEntry) GetDuration() string {
	if m != nil {
		return m.Duration
	}
	return ""
}

type Trace_Average struct {
	MsgName              string   `protobuf:"bytes,1,opt,name=msg_name,json=msgName,proto3" json:"msg_name,omitempty"`
	AverageTime          string   `protobuf:"bytes,2,opt,name=average_time,json=averageTime,proto3" json:"average_time,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Trace_Average) Reset()         { *m = Trace_Average{} }
func (m *Trace_Average) String() string { return proto.CompactTextString(m) }
func (*Trace_Average) ProtoMessage()    {}
func (*Trace_Average) Descriptor() ([]byte, []int) {
	return fileDescriptor_apitrace_cc9008d971ab8114, []int{0, 1}
}
func (m *Trace_Average) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Trace_Average.Unmarshal(m, b)
}
func (m *Trace_Average) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Trace_Average.Marshal(b, m, deterministic)
}
func (dst *Trace_Average) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Trace_Average.Merge(dst, src)
}
func (m *Trace_Average) XXX_Size() int {
	return xxx_messageInfo_Trace_Average.Size(m)
}
func (m *Trace_Average) XXX_DiscardUnknown() {
	xxx_messageInfo_Trace_Average.DiscardUnknown(m)
}

var xxx_messageInfo_Trace_Average proto.InternalMessageInfo

func (m *Trace_Average) GetMsgName() string {
	if m != nil {
		return m.MsgName
	}
	return ""
}

func (m *Trace_Average) GetAverageTime() string {
	if m != nil {
		return m.AverageTime
	}
	return ""
}

func init() {
	proto.RegisterType((*Trace)(nil), "apitrace.Trace")
	proto.RegisterType((*Trace_TracedEntry)(nil), "apitrace.Trace.TracedEntry")
	proto.RegisterType((*Trace_Average)(nil), "apitrace.Trace.Average")
}

func init() { proto.RegisterFile("apitrace.proto", fileDescriptor_apitrace_cc9008d971ab8114) }

var fileDescriptor_apitrace_cc9008d971ab8114 = []byte{
	// 236 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x90, 0xb1, 0x4e, 0xc3, 0x30,
	0x10, 0x86, 0xe5, 0x54, 0xa5, 0xe1, 0xd2, 0x74, 0xb0, 0x90, 0x30, 0x61, 0x09, 0x4c, 0x99, 0x3a,
	0xc0, 0xca, 0x02, 0x12, 0x62, 0x63, 0xb0, 0x32, 0xb1, 0x44, 0x06, 0x9f, 0x22, 0x4b, 0xb5, 0x5d,
	0xd9, 0x06, 0xc1, 0x1b, 0xf2, 0x58, 0x28, 0x89, 0x13, 0x92, 0x2e, 0x96, 0x3f, 0xeb, 0xbf, 0xef,
	0xce, 0x07, 0x3b, 0x71, 0x54, 0xc1, 0x89, 0x0f, 0xdc, 0x1f, 0x9d, 0x0d, 0x96, 0xa6, 0x23, 0xdf,
	0xfe, 0x26, 0xb0, 0xae, 0xbb, 0x1b, 0x7d, 0x82, 0x5d, 0xff, 0x24, 0x1b, 0x34, 0xc1, 0x29, 0xf4,
	0x8c, 0x94, 0xab, 0x2a, 0xbb, 0xbb, 0xde, 0x4f, 0xc5, 0xf5, 0xff, 0x29, 0x9f, 0x4d, 0x70, 0x3f,
	0x3c, 0x0f, 0x13, 0x28, 0xf4, 0xf4, 0x01, 0x72, 0xf1, 0x85, 0x4e, 0xb4, 0xd8, 0x04, 0xa5, 0xd1,
	0xb3, 0xa4, 0x57, 0x5c, 0x9e, 0x2a, 0x1e, 0x87, 0x10, 0xdf, 0xc6, 0x74, 0xdd, 0x85, 0x29, 0x83,
	0x8d, 0xed, 0xf8, 0x70, 0x60, 0xab, 0x92, 0x54, 0xe7, 0x7c, 0xc4, 0xe2, 0x0d, 0xb2, 0x59, 0x57,
	0x7a, 0x01, 0x6b, 0x65, 0x24, 0x7e, 0x33, 0x52, 0x92, 0x2a, 0xe7, 0x03, 0xd0, 0x2b, 0x48, 0xb5,
	0x6f, 0x1b, 0x23, 0x34, 0xb2, 0x64, 0xa8, 0xd7, 0xbe, 0x7d, 0x15, 0x1a, 0x69, 0x01, 0xa9, 0xfc,
	0x74, 0x22, 0x28, 0x6b, 0xa2, 0x7a, 0xe2, 0xe2, 0x05, 0x36, 0x71, 0x9c, 0x85, 0x81, 0x2c, 0x0d,
	0x37, 0xb0, 0x9d, 0xff, 0x2c, 0x36, 0xc8, 0x66, 0xf3, 0xbf, 0x9f, 0xf5, 0xbb, 0xbd, 0xff, 0x0b,
	0x00, 0x00, 0xff, 0xff, 0x90, 0xbd, 0xff, 0xe1, 0x6d, 0x01, 0x00, 0x00,
}
