#!/bin/bash

EXCLUDE_CONTENT="^// DO NOT EDIT|^// File generated by|^// Automatically generated|^// Code generated by protoc-gen-go. DO NOT EDIT.|^// Code generated by protoc-gen-gogo. DO NOT EDIT."
FILES_TO_EXCLUDE=$(echo $(echo $(grep -lrE "${EXCLUDE_CONTENT}" | grep '\.go' | fgrep -v vendor/ | sed -e "s/$/|/g") | sed -e "s/| /|/g") | sed -e "s/|$//g")

gometalinter --vendor --deadline 1m --enable-gc --disable-all --enable=golint --enable=vet --exclude=vendor --exclude="should not use dot imports" --exclude=$FILES_TO_EXCLUDE ./...
