// Copyright (c) 2018 Cisco and/or its affiliates.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at:
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	crdexample_io_v1 "github.com/ligato/cn-infra/examples/crd-plugin/pkg/apis/crdexample.io/v1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeCrdExampleEmbeds implements CrdExampleEmbedInterface
type FakeCrdExampleEmbeds struct {
	Fake *FakeCrdexampleV1
	ns   string
}

var crdexampleembedsResource = schema.GroupVersionResource{Group: "crdexample.io", Version: "v1", Resource: "crdexampleembeds"}

var crdexampleembedsKind = schema.GroupVersionKind{Group: "crdexample.io", Version: "v1", Kind: "CrdExampleEmbed"}

// Get takes name of the crdExampleEmbed, and returns the corresponding crdExampleEmbed object, and an error if there is any.
func (c *FakeCrdExampleEmbeds) Get(name string, options v1.GetOptions) (result *crdexample_io_v1.CrdExampleEmbed, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(crdexampleembedsResource, c.ns, name), &crdexample_io_v1.CrdExampleEmbed{})

	if obj == nil {
		return nil, err
	}
	return obj.(*crdexample_io_v1.CrdExampleEmbed), err
}

// List takes label and field selectors, and returns the list of CrdExampleEmbeds that match those selectors.
func (c *FakeCrdExampleEmbeds) List(opts v1.ListOptions) (result *crdexample_io_v1.CrdExampleEmbedList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(crdexampleembedsResource, crdexampleembedsKind, c.ns, opts), &crdexample_io_v1.CrdExampleEmbedList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &crdexample_io_v1.CrdExampleEmbedList{}
	for _, item := range obj.(*crdexample_io_v1.CrdExampleEmbedList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested crdExampleEmbeds.
func (c *FakeCrdExampleEmbeds) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(crdexampleembedsResource, c.ns, opts))

}

// Create takes the representation of a crdExampleEmbed and creates it.  Returns the server's representation of the crdExampleEmbed, and an error, if there is any.
func (c *FakeCrdExampleEmbeds) Create(crdExampleEmbed *crdexample_io_v1.CrdExampleEmbed) (result *crdexample_io_v1.CrdExampleEmbed, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(crdexampleembedsResource, c.ns, crdExampleEmbed), &crdexample_io_v1.CrdExampleEmbed{})

	if obj == nil {
		return nil, err
	}
	return obj.(*crdexample_io_v1.CrdExampleEmbed), err
}

// Update takes the representation of a crdExampleEmbed and updates it. Returns the server's representation of the crdExampleEmbed, and an error, if there is any.
func (c *FakeCrdExampleEmbeds) Update(crdExampleEmbed *crdexample_io_v1.CrdExampleEmbed) (result *crdexample_io_v1.CrdExampleEmbed, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(crdexampleembedsResource, c.ns, crdExampleEmbed), &crdexample_io_v1.CrdExampleEmbed{})

	if obj == nil {
		return nil, err
	}
	return obj.(*crdexample_io_v1.CrdExampleEmbed), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeCrdExampleEmbeds) UpdateStatus(crdExampleEmbed *crdexample_io_v1.CrdExampleEmbed) (*crdexample_io_v1.CrdExampleEmbed, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(crdexampleembedsResource, "status", c.ns, crdExampleEmbed), &crdexample_io_v1.CrdExampleEmbed{})

	if obj == nil {
		return nil, err
	}
	return obj.(*crdexample_io_v1.CrdExampleEmbed), err
}

// Delete takes name of the crdExampleEmbed and deletes it. Returns an error if one occurs.
func (c *FakeCrdExampleEmbeds) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(crdexampleembedsResource, c.ns, name), &crdexample_io_v1.CrdExampleEmbed{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeCrdExampleEmbeds) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(crdexampleembedsResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &crdexample_io_v1.CrdExampleEmbedList{})
	return err
}

// Patch applies the patch and returns the patched crdExampleEmbed.
func (c *FakeCrdExampleEmbeds) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *crdexample_io_v1.CrdExampleEmbed, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(crdexampleembedsResource, c.ns, name, data, subresources...), &crdexample_io_v1.CrdExampleEmbed{})

	if obj == nil {
		return nil, err
	}
	return obj.(*crdexample_io_v1.CrdExampleEmbed), err
}
