// Copyright (c) 2018 Cisco and/or its affiliates.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at:
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	crdexample_io_v1 "github.com/ligato/cn-infra/examples/crd-plugin/pkg/apis/crdexample.io/v1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeCrdExamples implements CrdExampleInterface
type FakeCrdExamples struct {
	Fake *FakeCrdexampleV1
	ns   string
}

var crdexamplesResource = schema.GroupVersionResource{Group: "crdexample.io", Version: "v1", Resource: "crdexamples"}

var crdexamplesKind = schema.GroupVersionKind{Group: "crdexample.io", Version: "v1", Kind: "CrdExample"}

// Get takes name of the crdExample, and returns the corresponding crdExample object, and an error if there is any.
func (c *FakeCrdExamples) Get(name string, options v1.GetOptions) (result *crdexample_io_v1.CrdExample, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(crdexamplesResource, c.ns, name), &crdexample_io_v1.CrdExample{})

	if obj == nil {
		return nil, err
	}
	return obj.(*crdexample_io_v1.CrdExample), err
}

// List takes label and field selectors, and returns the list of CrdExamples that match those selectors.
func (c *FakeCrdExamples) List(opts v1.ListOptions) (result *crdexample_io_v1.CrdExampleList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(crdexamplesResource, crdexamplesKind, c.ns, opts), &crdexample_io_v1.CrdExampleList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &crdexample_io_v1.CrdExampleList{}
	for _, item := range obj.(*crdexample_io_v1.CrdExampleList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested crdExamples.
func (c *FakeCrdExamples) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(crdexamplesResource, c.ns, opts))

}

// Create takes the representation of a crdExample and creates it.  Returns the server's representation of the crdExample, and an error, if there is any.
func (c *FakeCrdExamples) Create(crdExample *crdexample_io_v1.CrdExample) (result *crdexample_io_v1.CrdExample, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(crdexamplesResource, c.ns, crdExample), &crdexample_io_v1.CrdExample{})

	if obj == nil {
		return nil, err
	}
	return obj.(*crdexample_io_v1.CrdExample), err
}

// Update takes the representation of a crdExample and updates it. Returns the server's representation of the crdExample, and an error, if there is any.
func (c *FakeCrdExamples) Update(crdExample *crdexample_io_v1.CrdExample) (result *crdexample_io_v1.CrdExample, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(crdexamplesResource, c.ns, crdExample), &crdexample_io_v1.CrdExample{})

	if obj == nil {
		return nil, err
	}
	return obj.(*crdexample_io_v1.CrdExample), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeCrdExamples) UpdateStatus(crdExample *crdexample_io_v1.CrdExample) (*crdexample_io_v1.CrdExample, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(crdexamplesResource, "status", c.ns, crdExample), &crdexample_io_v1.CrdExample{})

	if obj == nil {
		return nil, err
	}
	return obj.(*crdexample_io_v1.CrdExample), err
}

// Delete takes name of the crdExample and deletes it. Returns an error if one occurs.
func (c *FakeCrdExamples) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(crdexamplesResource, c.ns, name), &crdexample_io_v1.CrdExample{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeCrdExamples) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(crdexamplesResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &crdexample_io_v1.CrdExampleList{})
	return err
}

// Patch applies the patch and returns the patched crdExample.
func (c *FakeCrdExamples) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *crdexample_io_v1.CrdExample, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(crdexamplesResource, c.ns, name, data, subresources...), &crdexample_io_v1.CrdExample{})

	if obj == nil {
		return nil, err
	}
	return obj.(*crdexample_io_v1.CrdExample), err
}
