// Copyright (c) 2018 Cisco and/or its affiliates.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at:
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by informer-gen. DO NOT EDIT.

package v1

import (
	time "time"

	crdexample_io_v1 "github.com/ligato/cn-infra/examples/crd-plugin/pkg/apis/crdexample.io/v1"
	versioned "github.com/ligato/cn-infra/examples/crd-plugin/pkg/client/clientset/versioned"
	internalinterfaces "github.com/ligato/cn-infra/examples/crd-plugin/pkg/client/informers/externalversions/internalinterfaces"
	v1 "github.com/ligato/cn-infra/examples/crd-plugin/pkg/client/listers/crdexample.io/v1"
	meta_v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// CrdExampleInformer provides access to a shared informer and lister for
// CrdExamples.
type CrdExampleInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1.CrdExampleLister
}

type crdExampleInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewCrdExampleInformer constructs a new informer for CrdExample type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewCrdExampleInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredCrdExampleInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredCrdExampleInformer constructs a new informer for CrdExample type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredCrdExampleInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options meta_v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.CrdexampleV1().CrdExamples(namespace).List(options)
			},
			WatchFunc: func(options meta_v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.CrdexampleV1().CrdExamples(namespace).Watch(options)
			},
		},
		&crdexample_io_v1.CrdExample{},
		resyncPeriod,
		indexers,
	)
}

func (f *crdExampleInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredCrdExampleInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *crdExampleInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&crdexample_io_v1.CrdExample{}, f.defaultInformer)
}

func (f *crdExampleInformer) Lister() v1.CrdExampleLister {
	return v1.NewCrdExampleLister(f.Informer().GetIndexer())
}
