apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: crdexample
spec:
  template:
    metadata:
      labels:
        app: crdexample-ds
    spec:
      nodeSelector:
        app: crdservice-node
      serviceAccountName: crdexample
      containers:
        - name: crd
          image: ligato/cn-infra/crdexample
          imagePullPolicy: IfNotPresent

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: crdexample

---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: crd-creater
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: crd-creater-binding
subjects:
- kind: ServiceAccount
  namespace: default
  name: networkservicemesh
roleRef:
  kind: ClusterRole
  name: crd-creater
  apiGroup: rbac.authorization.k8s.io
