// Copyright (c) 2018 Cisco and/or its affiliates.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at:
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	v1 "github.com/ligato/cn-infra/examples/crd-plugin/pkg/apis/crdexample.io/v1"
	scheme "github.com/ligato/cn-infra/examples/crd-plugin/pkg/client/clientset/versioned/scheme"
	meta_v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// CrdExamplesGetter has a method to return a CrdExampleInterface.
// A group's client should implement this interface.
type CrdExamplesGetter interface {
	CrdExamples(namespace string) CrdExampleInterface
}

// CrdExampleInterface has methods to work with CrdExample resources.
type CrdExampleInterface interface {
	Create(*v1.CrdExample) (*v1.CrdExample, error)
	Update(*v1.CrdExample) (*v1.CrdExample, error)
	UpdateStatus(*v1.CrdExample) (*v1.CrdExample, error)
	Delete(name string, options *meta_v1.DeleteOptions) error
	DeleteCollection(options *meta_v1.DeleteOptions, listOptions meta_v1.ListOptions) error
	Get(name string, options meta_v1.GetOptions) (*v1.CrdExample, error)
	List(opts meta_v1.ListOptions) (*v1.CrdExampleList, error)
	Watch(opts meta_v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1.CrdExample, err error)
	CrdExampleExpansion
}

// crdExamples implements CrdExampleInterface
type crdExamples struct {
	client rest.Interface
	ns     string
}

// newCrdExamples returns a CrdExamples
func newCrdExamples(c *CrdexampleV1Client, namespace string) *crdExamples {
	return &crdExamples{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the crdExample, and returns the corresponding crdExample object, and an error if there is any.
func (c *crdExamples) Get(name string, options meta_v1.GetOptions) (result *v1.CrdExample, err error) {
	result = &v1.CrdExample{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("crdexamples").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of CrdExamples that match those selectors.
func (c *crdExamples) List(opts meta_v1.ListOptions) (result *v1.CrdExampleList, err error) {
	result = &v1.CrdExampleList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("crdexamples").
		VersionedParams(&opts, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested crdExamples.
func (c *crdExamples) Watch(opts meta_v1.ListOptions) (watch.Interface, error) {
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("crdexamples").
		VersionedParams(&opts, scheme.ParameterCodec).
		Watch()
}

// Create takes the representation of a crdExample and creates it.  Returns the server's representation of the crdExample, and an error, if there is any.
func (c *crdExamples) Create(crdExample *v1.CrdExample) (result *v1.CrdExample, err error) {
	result = &v1.CrdExample{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("crdexamples").
		Body(crdExample).
		Do().
		Into(result)
	return
}

// Update takes the representation of a crdExample and updates it. Returns the server's representation of the crdExample, and an error, if there is any.
func (c *crdExamples) Update(crdExample *v1.CrdExample) (result *v1.CrdExample, err error) {
	result = &v1.CrdExample{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("crdexamples").
		Name(crdExample.Name).
		Body(crdExample).
		Do().
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().

func (c *crdExamples) UpdateStatus(crdExample *v1.CrdExample) (result *v1.CrdExample, err error) {
	result = &v1.CrdExample{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("crdexamples").
		Name(crdExample.Name).
		SubResource("status").
		Body(crdExample).
		Do().
		Into(result)
	return
}

// Delete takes name of the crdExample and deletes it. Returns an error if one occurs.
func (c *crdExamples) Delete(name string, options *meta_v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("crdexamples").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *crdExamples) DeleteCollection(options *meta_v1.DeleteOptions, listOptions meta_v1.ListOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("crdexamples").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched crdExample.
func (c *crdExamples) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1.CrdExample, err error) {
	result = &v1.CrdExample{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("crdexamples").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
